# Generated by Django 6.0 on 2025-12-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenis',
            name='DestaquePrincipal',
            field=models.BooleanField(default=False),
        ),
    ]
