# Generated by Django 6.0 on 2025-12-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0002_tenis_destaqueprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenis',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
