# Generated by Django 6.0 on 2026-01-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0003_tenis_preco_promocional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
