# Generated by Django 6.0 on 2026-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0004_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenis',
            options={'verbose_name': 'Tênis', 'verbose_name_plural': 'Tênis'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
